# Generated by Django 5.2.1 on 2025-05-23 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_alter_tasks_options_passwordresettoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='reminder',
            new_name='due_time',
        ),
        migrations.RemoveField(
            model_name='labels',
            name='color',
        ),
    ]
